language: node_js
node_js:
  - '4'

script:
  - npm test

# run on container-based infrastructure
sudo: false
cache:
  directories:
    - node_modules

addons:
  postgresql: "9.4"
  apt:
    packages:
    - pdftk

before_script:
  - psql -c 'create database test;' -U postgres

services:
  - postgresql
